name: CI

on:
  workflow_dispatch:
  push:
    branches: 
      - main

env:
  REGISTRY: ghcr.io

jobs:
  lint-and-test:
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}            

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-documentation:
    name: Deploy Documentation
    needs: lint-and-test
    runs-on: ubuntu-latest

    env:
      # Build target specifies which target in your Swift Package to build documentation for.
      # To build all targets, remove this env variable,
      # and remove --target arg in the building step below.
      BUILD_TARGET: AppApi
      BUILD_TARGET_LOWERCASE: appapi

    concurrency:
      group: "pages"
      cancel-in-progress: false

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/documentation/${{ env.BUILD_TARGET_LOWERCASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Swift Packages
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('./Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
          generate-documentation --target ${BUILD_TARGET} \
          --output-path ./docs \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path ${{ github.event.repository.name }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
